name: FluidaStatis
description: Aplikasi Edukasi Tentang Fluida Statis Dalam Fisika

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fluttertoast: ^7.1.6
  get: ^3.25.6
  chewie: ^0.12.2
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/materi1_1.jpeg
    - assets/images/materi1_2.jpeg
    - assets/images/materi1_3.jpeg
    - assets/images/materi1_4.jpeg
    - assets/images/materi1_5.jpeg
    - assets/images/materi2_1.jpeg
    - assets/images/materi2_2.jpeg
    - assets/images/materi2_3.jpeg
    - assets/images/materi2_5.jpeg
    - assets/images/materi2_6.jpeg
    - assets/images/materi2_7.jpeg
    - assets/images/materi2_8.jpeg
    - assets/images/materi2_9.jpeg
    - assets/images/materi2_10.jpeg
    - assets/images/materi2_11.jpeg
    - assets/images/materi2_12.jpeg
    - assets/images/materi2_13.jpeg
    - assets/images/materi3_1.jpeg
    - assets/images/materi3_2.jpeg
    - assets/images/materi3_3.jpeg
    - assets/images/materi4_1.jpeg
    - assets/images/materi4_2.jpeg
    - assets/images/materi4_3.jpeg
    - assets/images/materi4_4.jpeg
    - assets/images/materi4_5.jpeg
    - assets/images/materi4_6.jpeg
    - assets/images/materi5_1.jpeg
    - assets/images/materi5_2.jpeg
    - assets/images/materi5_3.jpeg
    - assets/images/profile.jpeg
    - assets/images/soal11.jpeg
    - assets/images/soal16.jpeg
    - assets/images/soal17.jpeg
    - assets/videos/video_hukum_archimedes.mp4
    - assets/videos/video_hukum_pascal.mp4
    - assets/videos/video_tegangan_permukaan.mp4
    - assets/videos/video_tekanan_hidrostatis.mp4


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PineappleGrass
      fonts:
        - asset: assets/fonts/PineappleGrass.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
